Repository ROCm/hip, pull requests merged in 2019-11, with the labels that each got.

#1615 [HIPIFY][CUB][#1460][perl] Add "cub::" namespace prefix support in hipify-perl as well
  bin/hipify-perl
  hipify-clang/src/CUDA2HIP_Perl.cpp
Labels: hipify, type:feature

#1617 [HIPIFY] Introduce --cuda-gpu-arch as hipify-clang's option
  hipify-clang/src/ArgParse.cpp
  hipify-clang/src/ArgParse.h
  hipify-clang/src/main.cpp
Labels: hipify, type:feature

#1613 [hip][tests] Add two more workgroup sizes for testing...
  tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp
Labels: pr:ready_to_merge

#1622 Deprecate HIP Markers
  CMakeLists.txt
  include/hip/hcc_detail/hip_runtime_api.h
  include/hip/hip_profile.h
Labels: pr:ready_to_merge

#1624 [HIPIFY][#1409] Fix for kernel launch macro expansion
  hipify-clang/src/HipifyAction.cpp
  tests/hipify-clang/unit_tests/kernel_launch/kernel_launch_01.cu
Labels: difficulty:B_Medium, hipify, type:fix

#1595 [HIP][cmake] Simplify `UNIX` related code (the beginning)
  CMakeLists.txt
Labels: hip, type:build, type:enhancement

#1633 [HIPIFY] Add a compatibility for CharSourceRange if LLVM < 7
  hipify-clang/src/HipifyAction.cpp
  hipify-clang/src/LLVMCompat.cpp
  hipify-clang/src/LLVMCompat.h
Labels: hipify, type:fix

#1634 [HIPIFY][format] Apply clang style formatting in LLVMCompat
  hipify-clang/src/LLVMCompat.cpp
  hipify-clang/src/LLVMCompat.h
Labels: hipify, type:formatting

#1635 [HIPIFY][doc] Update README.md
  hipify-clang/README.md
Labels: hipify, type:doc

#1636 [HIPIFY][Win][fix] canCompileHostAndDeviceInOneJob is true only for LLVM >= 10
  hipify-clang/src/LLVMCompat.cpp
Labels: hipify, type:fix

#1341 Rename hip/hip_hcc.h to hip/hip_ext.h
  include/hip/hcc_detail/macro_based_grid_launch.hpp
  include/hip/hip_ext.h
  include/hip/hip_hcc.h
  samples/0_Intro/module_api/launchKernelHcc.cpp
  samples/0_Intro/module_api_global/runKernel.cpp
  samples/2_Cookbook/11_texture_driver/texture2dDrv.cpp
  src/hip_hcc.cpp
  src/hip_module.cpp
  tests/src/hipHcc.cpp
  tests/src/runtimeApi/module/hipModuleGetGlobal.cpp
  tests/src/runtimeApi/module/hipModuleTexture2dDrv.cpp
Labels: pr:ready_to_merge

#1415 Fixed texture 2D mapping for pitched arrays & 3D Texture read
  include/hip/hcc_detail/hip_runtime_api.h
  src/hip_memory.cpp
  src/hip_texture.cpp
  tests/src/test_common.h
  tests/src/texture/hipBindTex2DPitch.cpp
  tests/src/texture/hipNormalizedFloatValueTex.cpp
  tests/src/texture/hipTexObjPitch.cpp
  tests/src/texture/simpleTexture2DLayered.cpp
  tests/src/texture/simpleTexture3D.cpp
Labels: pr:ready_to_merge

#1425 [HIP] Fixed hipStreamAddCallback [SWDEV#165185]
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
  src/hip_stream.cpp
  tests/src/runtimeApi/stream/StreamAddCallback.cpp
  tests/src/runtimeApi/stream/hipStreamAddCallbackCrossStream.cpp
  tests/src/runtimeApi/stream/hipStreamAddCallbackMultiThread.cpp
Labels: hip, pr:ready_to_merge, priority: P2 (important), type:fix

#1637 Remove native vector support from the GCC case, since it never worked
  include/hip/hcc_detail/hip_vector_types.h
Labels: pr:ready_to_merge

#1495 General hipMemset improvements
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1640 [HIPIFY] Reorder options propagation to clang
  hipify-clang/src/main.cpp
Labels: hipify, type:enhancement

#1641 [HIPIFY][fix] Abandon canCompileHostAndDeviceInOneJob check for --cuda-compile-host-device option
  hipify-clang/src/LLVMCompat.cpp
  hipify-clang/src/LLVMCompat.h
  hipify-clang/src/main.cpp
Labels: hipify, type:fix

#1642 [HIPIFY] Clang style formatting
  hipify-clang/src/CUDA2HIP_Perl.cpp
  hipify-clang/src/CUDA2HIP_Python.cpp
  hipify-clang/src/HipifyAction.cpp
  hipify-clang/src/ReplacementsFrontendActionFactory.h
  hipify-clang/src/Statistics.cpp
  hipify-clang/src/Statistics.h
  hipify-clang/src/StringUtils.cpp
  hipify-clang/src/StringUtils.h
Labels: hipify, type:formatting

#1651 [HIPIFY][doc] A few words about LLVM's FileCheck in README.md
  hipify-clang/README.md
Labels: hipify, type:doc

#1608 Fixing compilation error in saxpy.cpp
  tests/src/hiprtc/saxpy.cpp
Labels: pr:ready_to_merge

#1614 Updated hipEnvVarDriver to work with Windows
  tests/src/hipEnvVarDriver.cpp
  tests/src/test_common.cpp
  tests/src/test_common.h
Labels: pr:ready_to_merge

#1627 Added null check in hipEventSynchronize
  include/hip/hcc_detail/hip_runtime_api.h
  src/hip_event.cpp
Labels: pr:ready_to_merge

#1659 fix complex conjugate for double-complex
  include/hip/hcc_detail/hip_complex.h
Labels: pr:ready_to_merge

#1661 Fix gcc build on NVCC path
  include/hip/nvcc_detail/hip_runtime_api.h
  tests/src/gcc/hipMalloc.c
  tests/src/surface/hipSurfaceObj2D.cpp
  tests/src/texture/hipTextureObj2D.cpp
Labels: pr:ready_to_merge

#1671 [dtest] Rename hipExtLaunchMultiKernelMultiDevice dtest
  tests/src/runtimeApi/module/hipExtLaunchMultiKernelMultiDevice.cpp
Labels: pr:ready_to_merge

#1667 hipStreamSynchronize can skip marker if stream is empty
  src/hip_hcc.cpp
Labels: pr:ready_to_merge

#1674 Revert [HIP] Fixed hipStreamAddCallback
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
  src/hip_stream.cpp
  tests/src/runtimeApi/stream/StreamAddCallback.cpp
  tests/src/runtimeApi/stream/hipStreamAddCallbackCrossStream.cpp
  tests/src/runtimeApi/stream/hipStreamAddCallbackMultiThread.cpp
Labels: hip, priority: P1 (critical)

#1656 Extend vector type capabilities and add tests to reflect it.
  include/hip/hcc_detail/hip_vector_types.h
  tests/src/deviceLib/hipVectorTypes.cpp
  tests/src/deviceLib/hipVectorTypesDevice.cpp
Labels: pr:ready_to_merge

#1666 Fix helper header when using c++17
  include/hip/hcc_detail/helpers.hpp
  tests/src/cppstd/hipInvocable11.cpp
  tests/src/cppstd/hipInvocable11Fallback.cpp
  tests/src/cppstd/hipInvocable14.cpp
  tests/src/cppstd/hipInvocable17.cpp
  tests/src/cppstd/is_callable_test.hpp
Labels: pr:ready_to_merge

#1668 Update error codes for hipGetDevice for doxygen and move up null check
  include/hip/hcc_detail/hip_runtime_api.h
  src/hip_device.cpp
Labels: pr:ready_to_merge

#1673 General sync memcpy improvements. Add `hipMemcpyWithStream`
  include/hip/hcc_detail/hip_runtime_api.h
  include/hip/nvcc_detail/hip_runtime_api.h
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1678 fixed directed tests fail when hcc bumped to 3.0
  include/hip/hcc_detail/device_functions.h
  include/hip/hcc_detail/device_library_decls.h
  src/hip_stream.cpp
Labels: pr:ready_to_merge

#1591 Use native support for atomic FADD when address is in LDS
  include/hip/hcc_detail/hip_atomic.h
  tests/src/deviceLib/hipSimpleAtomicsTest.cpp
Labels: pr:ready_to_merge

#1677 Fix rocBLAS compilation failure
  include/hip/hip_ext.h
Labels: pr:ready_to_merge

#1681 [HIPIFY] fix typo
  hipify-clang/src/ArgParse.cpp
Labels: pr:ready_to_merge

#1683 Unary operators were too restrictive in the type of their argument.
  include/hip/hcc_detail/hip_vector_types.h
Labels: pr:ready_to_merge

#1702 [HIPIFY] Sync cudaError/CUresult between CUDA Driver API/CUDA RT API/HIP
  bin/hipify-perl
  docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_Driver_API_types.cpp
  hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
Labels: hipify
