Repository ROCm/hip, pull requests merged in 2020-03, with the labels that each got.

#1905 [HIP][cmake] Remove dependency from hipify-clang
  CMakeLists.txt
Labels: type:build

#1914 [HIPIFY][doc] Update README.md: LLVM 10.0.0-rc3 is supported
  hipify-clang/README.md
Labels: type:doc

#1922 [HIP][doc] Update README.md
  README.md
Labels: type:doc

#1925 Fix incorrect shfl_xor for Windows
  include/hip/hcc_detail/device_functions.h
Labels: hip, type:fix

#1900 return hipSuccess when count is zero
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1909 Expose support for non-returning atomic FADD
  include/hip/hcc_detail/device_library_decls.h
  include/hip/hcc_detail/hip_atomic.h
Labels: pr:ready_to_merge

#1908 [HIP] add hip specific properties for cooperative kernel multi device
  include/hip/hip_runtime_api.h
  include/hip/nvcc_detail/hip_runtime_api.h
  src/hip_device.cpp
  src/hip_hcc.cpp
Labels: hip

#1916 [HIP] Refactor cooperative APIs
  src/hip_hcc.cpp
  src/hip_module.cpp
Labels: hip

#1873 [hip] Improve the portability of the header for vector type support.
  include/hip/hcc_detail/hip_vector_types.h
Labels: pr:ready_to_merge

#1901 Annotate `__constant__`
  include/hip/hcc_detail/host_defines.h
Labels: pr:ready_to_merge

#1924 Let hipcc not pass -mllvm option to HIP-Clang on Windows
  bin/hipcc
Labels: pr:ready_to_merge

#1926 Fix errors in occupancy calculation function
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1927 Fix maxSharedMemoryPerMultiProcessor attribute
  samples/1_Utils/hipInfo/hipInfo.cpp
  src/hip_hcc.cpp
Labels: pr:ready_to_merge, type:fix

#1929 [HIP] add cooperative kernel launch APIs on NVCC
  include/hip/nvcc_detail/hip_runtime_api.h
Labels: pr:ready_to_merge

#1931 Don't force compiler to treat libhip_hcc.so as a text file
  bin/hipcc
Labels: pr:ready_to_merge

#1932 Fix detection of support for cooperative groups
  src/hip_hcc.cpp
Labels: pr:ready_to_merge, type:fix

#1936 Fix __sad signature match with Cuda
  include/hip/hcc_detail/device_functions.h
Labels: pr:ready_to_merge, type:fix

#1938 Output file name should not change flags picked for compiler
  bin/hipcc
Labels: pr:ready_to_merge

#1941 Fix occupancy calculations API on NVCC
  include/hip/nvcc_detail/hip_runtime_api.h
Labels: hip, pr:ready_to_merge, type:fix

#1942 Fix compiler warning on NVCC path
  include/hip/nvcc_detail/hip_runtime_api.h
Labels: hip, pr:ready_to_merge, type:fix

#1947 enable HCC printf when using hip-clang
  include/hip/hcc_detail/device_functions.h
  include/hip/hcc_detail/hip_runtime.h
Labels: pr:ready_to_merge

#1949 fix a bug when initializing a vector of hipFunction_t
  src/hip_clang.cpp
Labels: pr:ready_to_merge, type:fix

#1951 [HIPIFY][doc] Update README.md: LLVM 10.0.0-rc4 is supported
  hipify-clang/README.md
Labels: type:doc

#1230 Add missing flags for hip::device target on hip-clang
  hip-config-clang.cmake.in
Labels: pr:ready_to_merge

#1676 Implement accurate max block size in hipFuncGetAttributes()
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1917 Workaround for libc++ include path for HIP-Clang
  bin/hipcc
  include/hip/hcc_detail/hip_runtime.h
Labels: pr:ready_to_merge, type:fix

#1948 [HIP] use markers to sync cooperative and normal queues
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1950 Remove debug message from FindHIP.cmake
  cmake/FindHIP.cmake
Labels: pr:ready_to_merge

#1953 [HIPIFY][SPARSE] sync with hipSPARSE
  bin/hipify-perl
  docs/markdown/CUSPARSE_API_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp
  hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp
  tests/hipify-clang/unit_tests/libraries/cuSPARSE/cuSPARSE_12.cu
Labels: hipify

#1954 [HIPIFY][SPARSE] sync with hipSPARSE's "added csrsm2" (#83)
  bin/hipify-perl
  docs/markdown/CUSPARSE_API_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp
  hipify-clang/src/CUDA2HIP_SPARSE_API_types.cpp
Labels: hipify

#1955 [HIPIFY][perl] Fix missed sync with hipify-clang
  bin/hipify-perl
  hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp
Labels: hipify, type:fix

#1913 packaging: change Provides to use dash instead of underscore
  packaging/hip-base.txt
  packaging/hip-doc.txt
  packaging/hip-hcc.txt
  packaging/hip-nvcc.txt
  packaging/hip-samples.txt
Labels: pr:ready_to_merge

#1934 fix hipStreamAddCallback, block future work on stream
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
  src/hip_stream.cpp
  tests/src/runtimeApi/stream/StreamAddCallback.cpp
  tests/src/runtimeApi/stream/hipStreamAddCallbackCatch.cpp
Labels: pr:ready_to_merge

#1945 Let hipcc treat .c program as C program
  bin/hipcc
Labels: pr:ready_to_merge

#1935 Fix cooperative launch APIs to set hipGetLastError
  include/hip/hcc_detail/functional_grid_launch.hpp
  src/hip_module.cpp
Labels: pr:ready_to_merge, type:fix

#1957 Add option --hipcc-func-supp for function support
  bin/hipcc
Labels: pr:ready_to_merge

#1961 Fix path for hip-clang when using hipcc
  hip-config-clang.cmake.in
Labels: pr:ready_to_merge

#1978 [HIPIFY][doc] Update README.md: LLVM 10.0.0 Release is supported
  hipify-clang/README.md
Labels: type:doc

#1732 [dtest] Adding VectorTest
  tests/src/deviceLib/hip_floatnTM.cpp
Labels: pr:ready_to_merge

#1937 Fix segfault seen in hipMemcpy [SWDEV-224941]
  src/hip_memory.cpp
  tests/src/runtimeApi/memory/hipMemcpyNegetiveTests.cpp
Labels: pr:ready_to_merge, type:fix

#1962 Ignore undef symbols from the static constexpr members in Coordinates
  src/program_state.inl
Labels: pr:ready_to_merge, priority: P1 (critical)

#1965 Add const qualifiers to HIP_vector_type unary arithmetic operators
  include/hip/hcc_detail/hip_vector_types.h
Labels: pr:ready_to_merge, type:fix

#1972 Fix for __usad issue reported #1930
  include/hip/hcc_detail/device_functions.h
  include/hip/hcc_detail/device_library_decls.h
Labels: pr:ready_to_merge, type:fix

#1973 [docs] Update hip_debugging.md
  docs/markdown/hip_debugging.md
Labels: pr:ready_to_merge

#1977 [hip] fix a build error when building hip with latest hcc
  src/hip_module.cpp
Labels: type:fix

#1918 Packaging changes to bring them to sync with generated ones
  packaging/hip-targets-release.cmake
  packaging/hip-targets.cmake
Labels: pr:ready_to_merge

#1969 Fix few memory leaks in HIP
  samples/0_Intro/module_api/defaultDriver.cpp
  samples/0_Intro/module_api/launchKernelHcc.cpp
  samples/0_Intro/module_api/runKernel.cpp
  samples/0_Intro/module_api_global/runKernel.cpp
  src/hip_module.cpp
  src/hip_texture.cpp
  tests/src/runtimeApi/module/hipModuleLoadDataMultThreaded.cpp
Labels: pr:ready_to_merge, type:fix

#1971 don't expose symbols from code_object_bundle
  CMakeLists.txt
  include/hip/hcc_detail/hiprtc.h
  lpl_ca/CMakeLists.txt
  lpl_ca/ca.hpp
  src/code_object_bundle.cpp
  src/code_object_bundle.inl
  src/hip_module.cpp
  src/hiprtc.cpp
  src/program_state.inl
Labels: pr:ready_to_merge

#1956 Remove address_space(1) typecast and use __ockl_atomic_add_noret_f32
  include/hip/hcc_detail/device_library_decls.h
  include/hip/hcc_detail/hip_atomic.h
Labels: pr:ready_to_merge

#1964 Fix for Segfault seen in hipMemcpyDtoD [SWDEV-227444]
  src/hip_memory.cpp
Labels: pr:ready_to_merge, type:fix
