Repository ROCm/hip, pull requests merged in 2020-04, with the labels that each got.

#1772 tex1Dfetch behaviour for different address mode and filter mode
  src/hip_texture.cpp
  tests/src/texture/hipTex1DFetchCheckModes.cpp
Labels: pr:ready_to_merge

#1989 adding hipApiString
  hip_prof_gen.py
Labels: pr:ready_to_merge

#1976 Fix ambiguity of fma for _Float16 for libc++
  include/hip/hcc_detail/math_functions.h
Labels: pr:ready_to_merge

#1980 Initial support for bfloat16
  include/hip/hip_bfloat16.h
  tests/src/deviceLib/hipBfloat16.cpp
Labels: pr:ready_to_merge

#1987 Fix 2D and 3D memset
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1988 Removing header size from formula
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1991 Don't duplicate embedded code objects
  include/hip/hcc_detail/program_state.hpp
  src/hip_clang.cpp
  src/program_state.cpp
  src/program_state.inl
Labels: pr:ready_to_merge

#1992 hipEventElapsedTime should respect device
  src/hip_event.cpp
  src/hip_hcc_internal.h
  tests/src/runtimeApi/event/hipEventElapsedTime.cpp
Labels: pr:ready_to_merge

#1993 Bump version to 3.5
  Jenkinsfile
  bin/hipconfig
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1994 use hsa_executable_get_symbol_by_name in find_kernel_by_name
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1998 fix hipIpcOpenMemHandle
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1943 Rename hipDrvOccupancy to hipModuleOccupancy and match CUDA syntax
  include/hip/hcc_detail/functional_grid_launch.hpp
  include/hip/hcc_detail/hip_runtime_api.h
  include/hip/nvcc_detail/hip_runtime_api.h
  samples/2_Cookbook/13_occupancy/occupancy.cpp
  src/hip_module.cpp
  tests/src/runtimeApi/module/hipLaunchCoopMultiKernel.cpp
  tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp
  tests/src/runtimeApi/module/hipModuleOccupancyMaxPotentialActiveBlockSize.cpp
  tests/src/runtimeApi/occupancy/hipOccupancyMaxActiveBlocksPerMultiprocessor.cpp
  tests/src/runtimeApi/occupancy/hipOccupancyMaxPotentialBlockSize.cpp
Labels: pr:ready_to_merge

#2001 [HIP][doc] Update docs due to moving of HIPIFY to a separate repo
  README.md
  docs/doxygen-input/mainpage.txt
  docs/markdown/hip_faq.md
  docs/markdown/hip_kernel_language.md
  docs/markdown/hip_porting_driver_api.md
  docs/markdown/hip_porting_guide.md
  docs/markdown/hip_terms2.md
  packaging/convert_md_to_html.sh
  samples/0_Intro/square/README.md
  samples/2_Cookbook/0_MatrixTranspose/Readme.md
  samples/2_Cookbook/10_inline_asm/Readme.md
  samples/2_Cookbook/12_cmake_hip_add_executable/Readme.md
  samples/2_Cookbook/1_hipEvent/Readme.md
  samples/2_Cookbook/3_shared_memory/Readme.md
  samples/2_Cookbook/4_shfl/Readme.md
  samples/2_Cookbook/5_2dshfl/Readme.md
  samples/2_Cookbook/6_dynamic_shared/Readme.md
  samples/2_Cookbook/7_streams/Readme.md
  samples/2_Cookbook/9_unroll/Readme.md
Labels: hip, hipify, pr:ready_to_merge, type:doc

#1990 [HIP] add support for NoPreSync/NoPostSync flags for Cooperative Mult…
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
  src/hip_memory.cpp
  src/hip_module.cpp
Labels: hip, type:feature

#2016 [HIP][SPARSE] sync with HIPIFY's #95 and #96
  bin/hipify-perl
  docs/markdown/CUSPARSE_API_supported_by_HIP.md
Labels: hipify, sync

#1644 moving the extractkernel tool from hcc to hip
  bin/extractkernel
Labels: pr:ready_to_merge

#1996 add IPC event support
  include/hip/hcc_detail/hip_runtime_api.h
  src/hip_event.cpp
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
  src/hip_stream.cpp
  src/trace_helper.h
  tests/src/runtimeApi/event/hipEventIpc.cpp
Labels: pr:ready_to_merge, priority: P2 (important)

#2017 [HIPTEST]common changes for unittest
  CMakeLists.txt
  tests/unit/test_common.cpp
  tests/unit/test_common.h
Labels: pr:ready_to_merge, type:test

#2021 disable printf on hip-clang on Windows
  include/hip/hcc_detail/device_functions.h
Labels: type:fix

#2029 Add __HIP_PLATFORM_HCC__ to hip::host target
  hip-config.cmake.in
Labels: pr:ready_to_merge

#2034 extractkernel obj dump args to use double dashes
  bin/extractkernel
Labels: pr:ready_to_merge

#2035 Fix hip-config.cmake for CMAKE_CXX_COMPILER=g++
  hip-config.cmake.in
Labels: pr:ready_to_merge

#2041 [HIP][BLAS] Sync with HIPIFY's #99 and #100
  bin/hipify-perl
  docs/markdown/CUBLAS_API_supported_by_HIP.md
Labels: hipify, sync, type:doc

#2043 [HIP][fix][sync] Fix HIP_MEMCPY3D to be in sync with CUDA_MEMCPY3D
  include/hip/hcc_detail/driver_types.h
Labels: hip, sync, type:fix

#2051 [HIPIFY][HIP][doc] Sync with HIPIFY's #102 (#2051)
  bin/hipify-perl
  docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
Labels: hip, hipify, sync, type:doc

#1999 Remove default sync in hostMalloc
  src/hip_hcc.cpp
Labels: pr:ready_to_merge

#2026 Let hipcc treats .cpp files as C++ files for HIP-Clang
  bin/hipcc
Labels: pr:ready_to_merge

#2038 Define missing flags for hipSetDeviceFlags on nvcc
  include/hip/nvcc_detail/hip_runtime_api.h
Labels: pr:ready_to_merge

#2046 Update hipconfig to support HIP-Clang
  bin/hipcc
  bin/hipconfig
Labels: pr:ready_to_merge

#2047 Fix channelFormatDescriptor typos on HIP/VDI
  include/hip/hcc_detail/hip_runtime_api.h
Labels: pr:ready_to_merge

#2052 remove a redundant operation
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#2053 Call ihip function for device synchronization in ihipHostMalloc
  src/hip_memory.cpp
Labels: pr:ready_to_merge
