Repository ROCm/hip, pull requests merged in 2020-01, with the labels that each got.

#1717 Document FMA settings
  docs/markdown/hip_programming_guide.md
Labels: pr:ready_to_merge

#1764 Update HIP-Clang build instruction
  INSTALL.md
Labels: pr:ready_to_merge

#1767 Fix hipcc warning related to hipVersion
  .gitignore
  CMakeLists.txt
  bin/hipcc
  include/hip/hip_runtime.h
Labels: pr:ready_to_merge

#1768 Fix nested designator warnings
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1773 Add hipBindTexture2D on NVCC path
  include/hip/nvcc_detail/hip_runtime_api.h
  tests/src/texture/hipBindTex2DPitch.cpp
Labels: pr:ready_to_merge

#1775 Fix minor explainations in the kernel guide
  docs/markdown/hip_kernel_language.md
Labels: pr:ready_to_merge

#1774 hipMemcpysymbol fixes
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1777 Fix rocFFT build failure
  include/hip/hcc_detail/hip_complex.h
Labels: pr:ready_to_merge

#1779 [HIPIFY] main source file refactoring
  hipify-clang/src/main.cpp
Labels: hipify, type:enhancement

#1784 Fix test hip_bitextract.cpp
  tests/src/deviceLib/hip_bitextract.cpp
Labels: pr:ready_to_merge

#1778 [HIP] Unify hipError_t (Step 3): Sync nvcc path
  hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
  include/hip/nvcc_detail/hip_runtime_api.h
Labels: hip, pr:ready_to_merge

#1749 Remove filesystem dependency in hipRTC
  CMakeLists.txt
  src/hiprtc.cpp
Labels: pr:ready_to_merge

#1787 [HIPIFY] Sync with hipSPARSE
  bin/hipify-perl
  docs/markdown/CUSPARSE_API_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_SPARSE_API_functions.cpp
Labels: hipify

#1788 [HIPIFY][fix] Add "--" separator in-place if needed
  hipify-clang/src/main.cpp
Labels: hipify, type:fix

#1785 Fix texture tests, always pass row pitch to HSA API for linear layout…
  src/hip_hcc_internal.h
  src/hip_memory.cpp
  src/hip_texture.cpp
Labels: pr:ready_to_merge

#1795 [HIPIFY][cmake] Packaging for hipify-clang
  hipify-clang/CMakeLists.txt
  hipify-clang/packaging/hipify-clang.txt
  packaging/hip-base.txt
Labels: hipify, type:build

#1810 [HIPIFY][cmake] Send error on CUDA 10.2 and higher as yet unsupported
  hipify-clang/CMakeLists.txt
Labels: hipify, type:build

#1811 [HIPIFY][cmake] Formatting
  hipify-clang/CMakeLists.txt
Labels: hipify, type:formatting

#1812 [HIPIFY][doc] Readme - update versions
  hipify-clang/README.md
Labels: hipify, type:doc

#1786 Clear `HIP_PATH` before version detection
  CMakeLists.txt
Labels: pr:ready_to_merge

#1799 Fix associate code object symbols with host allocation bug
  src/program_state.cpp
  src/program_state.inl
  tests/src/kernel/hipPrintfKernel.cpp
Labels: pr:ready_to_merge

#1805 Fix install script syntax error
  packaging/hip-nvcc.postinst
  packaging/hip-nvcc.prerm
Labels: pr:ready_to_merge

#1808 SWDEV-220503: this_grid().thread_rank() gives incorrect result
  include/hip/hcc_detail/hip_cooperative_groups_helper.h
Labels: pr:ready_to_merge

#1814 Fix for a syntax error in deb packages
  hipify-clang/packaging/hipify-clang.txt
Labels: pr:ready_to_merge

#1813 [HIP][HIPIFY] Readmes actualization
  README.md
  hipify-clang/README.md
  hipify-clang/src/main.cpp
Labels: hip, hipify, type:doc

#1820 [HIPIFY] Update Readme.md
  hipify-clang/README.md
Labels: hipify, type:doc
