Repository ROCm/hip, pull requests merged in 2020-02, with the labels that each got.

#1838 [HIPIFY] Fix build failure against ToT trunk LLVM 11.0.0
  hipify-clang/src/HipifyAction.cpp
  hipify-clang/src/LLVMCompat.cpp
  hipify-clang/src/main.cpp
Labels: hipify, type:fix

#1839 [HIPIFY][cmake] CUDA 10.2 support starting from LLVM 10.0
  hipify-clang/CMakeLists.txt
Labels: hipify, type:build

#1840 [HIPIFY][doc] CUDA 10.2 is now supported by LLVM 10.0.0-rc1
  hipify-clang/README.md
Labels: hipify, type:doc

#1841 [HIPIFY][doc] Update README.md
  hipify-clang/README.md
Labels: hipify, type:doc, type:enhancement

#1731 [dtest] RCCL multi device launch test
  tests/src/runtimeApi/module/hipLaunchCoopMultiKernel.cpp
Labels: pr:ready_to_merge

#1800 Added support to disable test based on HIP Runtime(HCC/VDI) and Compi…
  tests/README.md
  tests/hit/HIT.cmake
Labels: pr:ready_to_merge

#1821 hipcc script: Refined device selection; added gfx1011 target.
  bin/hipcc
Labels: pr:ready_to_merge

#1824 [docs] Fix links in cookbook samples
  samples/2_Cookbook/0_MatrixTranspose/Readme.md
  samples/2_Cookbook/10_inline_asm/Readme.md
  samples/2_Cookbook/12_cmake_hip_add_executable/Readme.md
  samples/2_Cookbook/1_hipEvent/Readme.md
  samples/2_Cookbook/2_Profiler/Readme.md
  samples/2_Cookbook/3_shared_memory/Readme.md
  samples/2_Cookbook/4_shfl/Readme.md
  samples/2_Cookbook/5_2dshfl/Readme.md
  samples/2_Cookbook/6_dynamic_shared/Readme.md
  samples/2_Cookbook/7_streams/Readme.md
  samples/2_Cookbook/9_unroll/Readme.md
Labels: pr:ready_to_merge

#1831 Cmake package
  packaging/hip-targets-release.cmake
  packaging/hip-targets.cmake
Labels: pr:ready_to_merge

#1834 [HIP] Update INSTALL.md
  INSTALL.md
Labels: hip, pr:ready_to_merge, type:build

#1770 Added overflow check in kernel launch
  docs/markdown/hip_faq.md
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1835 Fix C-style hipLaunchKernel
  src/hip_module.cpp
  src/program_state.inl
  tests/src/gcc/LaunchKernel.c
  tests/src/gcc/LaunchKernel.h
  tests/src/gcc/gpu.cpp
Labels: pr:ready_to_merge

#1844 Update hipLaunchCoopMultiKernel.cpp at the line 159
  tests/src/runtimeApi/module/hipLaunchCoopMultiKernel.cpp
Labels: pr:ready_to_merge

#1845 Implement __hipPushCallConfiguration/__hipPopCallConfiguration for hip_clang
  src/hip_clang.cpp
Labels: pr:ready_to_merge

#1826 Device texture functions should not normalize the sampled pixel. This…
  include/hip/hcc_detail/hip_texture_types.h
  include/hip/hcc_detail/texture_functions.h
  include/hip/hcc_detail/texture_types.h
  src/hip_texture.cpp
  tests/src/texture/hipNormalizedFloatValueTex.cpp
Labels: pr:ready_to_merge

#1836 Enable code object v3 codgen when compiling with HCC
  bin/hipcc
Labels: pr:ready_to_merge

#1847 [hip] Revise compiler wrapper for HIP-Clang.
  bin/hipcc
Labels: pr:ready_to_merge

#1789 (Maybe) Match alignment between Clang and GCC.
  .gitignore
  include/hip/hcc_detail/hip_vector_types.h
Labels: pr:ready_to_merge

#1857 Revert "Match Occupancy APIs syntax with CUDA (#1625)"
  include/hip/hcc_detail/functional_grid_launch.hpp
  include/hip/hcc_detail/hip_runtime_api.h
  samples/2_Cookbook/13_occupancy/occupancy.cpp
  src/hip_module.cpp
  tests/src/runtimeApi/module/hipLaunchCooperativeKernel.cpp
  tests/src/runtimeApi/module/hipOccupancyMaxActiveBlocksPerMultiprocessor.cpp
  tests/src/runtimeApi/module/hipOccupancyMaxPotentialBlockSize.cpp
Labels: pr:ready_to_merge

#1860 Revert "Cmake package"
  packaging/hip-targets-release.cmake
  packaging/hip-targets.cmake
Labels: pr:ready_to_merge

#1830 [HIP][HIPIFY] Add some missing flags for cooperative launch and occup…
  bin/hipify-perl
  docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  docs/markdown/CUDA_Runtime_API_functions_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_Driver_API_types.cpp
  hipify-clang/src/CUDA2HIP_Runtime_API_types.cpp
  include/hip/hcc_detail/hip_runtime_api.h
  include/hip/hip_runtime_api.h
  include/hip/nvcc_detail/hip_runtime_api.h
  src/hip_hcc.cpp
Labels: hip, hipify

#1751 Reduce GPU copying based on arch it runs on
  CMakeLists.txt
  include/hip/hcc_detail/code_object_bundle.hpp
  lpl_ca/CMakeLists.txt
  src/hip_hcc.cpp
  src/program_state.inl
Labels: pr:ready_to_merge

#1858 Fix ihipEnablePeerAccess return if peer is not accessible
  src/hip_peer.cpp
Labels: pr:ready_to_merge

#1864 [hip] Fix for bug introduced in #1770 when blockSize is non-power of 2
  src/hip_module.cpp
Labels: hip, pr:ready_to_merge, type:fix

#1865 missing break statement in hipDeviceGetAttribute
  src/hip_device.cpp
Labels: pr:ready_to_merge

#1867 [HIPIFY][doc] Update README.md: Windows tested configurations
  hipify-clang/README.md
Labels: hipify, type:doc

#1870 [HIPIFY][doc] Update README.md: LLVM 10.0.0-rc2 - the latest supported LLVM Release
  hipify-clang/README.md
Labels: hipify, type:doc

#1829 Implement long / long long shuffles
  include/hip/hcc_detail/device_functions.h
  tests/src/kernel/hipShflTests.cpp
Labels: pr:ready_to_merge

#1851 Use deque instead of vector for code readers so that the iterators and references will be stable
  Jenkinsfile
  src/program_state.inl
  tests/src/runtimeApi/module/hipModuleLoadDataMultThreaded.cpp
Labels: pr:ready_to_merge

#1866 Add missing __hip_pinned_shadow__ attributes to the texture global vars.
  tests/src/texture/hipBindTex2DPitch.cpp
  tests/src/texture/hipNormalizedFloatValueTex.cpp
  tests/src/texture/simpleTexture2DLayered.cpp
  tests/src/texture/simpleTexture3D.cpp
Labels: pr:ready_to_merge

#1798 Fix hipMemcpy3D
  include/hip/hcc_detail/driver_types.h
  src/hip_memory.cpp
  tests/src/runtimeApi/memory/hipMemcpy3D.cpp
  tests/src/texture/simpleTexture2DLayered.cpp
  tests/src/texture/simpleTexture3D.cpp
Labels: pr:ready_to_merge

#1875 Let HIP-Clang inline all functions by default
  bin/hipcc
Labels: pr:ready_to_merge

#1809 Tweak synchronous memcpy implementation
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1885 Fix hipcc for extra -mllvm option
  bin/hipcc
Labels: pr:ready_to_merge

#1895 fix long shuffle implementations for windows
  include/hip/hcc_detail/device_functions.h
Labels: pr:ready_to_merge

#1894 Address post-staging issues in #1809
  src/hip_memory.cpp
Labels: pr:ready_to_merge

#1825 Cleaned up error messages for HipEnvVarDriver test
  tests/src/hipEnvVarDriver.cpp
  tests/src/test_common.cpp
  tests/src/test_common.h
Labels: pr:ready_to_merge

#1854 Add hipDrvOccupancyMaxActiveBlocksPerMultiprocessor
  docs/markdown/CUDA_Driver_API_functions_supported_by_HIP.md
  hipify-clang/src/CUDA2HIP_Driver_API_functions.cpp
  include/hip/hcc_detail/hip_runtime_api.h
  src/hip_module.cpp
Labels: pr:ready_to_merge

#1876 Remove deprecated HIP markers
  CMakeLists.txt
  bin/hipcc
  docs/markdown/hip_profiling.md
  docs/markdown/hip_tracing.md
  include/hip/hip_profile.h
  packaging/hip-hcc.txt
  samples/2_Cookbook/2_Profiler/Makefile
  samples/2_Cookbook/2_Profiler/MatrixTranspose.cpp
  samples/2_Cookbook/2_Profiler/Readme.md
  src/hip_hcc.cpp
  src/hip_hcc_internal.h
Labels: pr:ready_to_merge

#1879 Fix HIPRTC headers to export C style symbols
  include/hip/hcc_detail/hiprtc.h
  src/hiprtc.cpp
  tests/src/hiprtc/hiprtcGetTypeName.cpp
Labels: pr:ready_to_merge

#1889 improve code object loading error message
  src/program_state.inl
Labels: pr:ready_to_merge

#1899 [dtests] __shfl_up and __shfl_down tests
  tests/src/kernel/hipShflUpDownTest.cpp
Labels: pr:ready_to_merge
